// Generado por tools/rasterizar-mundo.mjs — no editar a mano.
// Natural Earth 110m (dominio público) rasterizado a 180×72 celdas.

export const MUNDO = {
  ancho: 180,
  alto: 72,
  latMax: 80,
  latMin: -64,
  /** Un bit por celda, en orden de lectura, empaquetado a base64. */
  bits: "AAAAAGC4D////wAAHwAAAAA8AAAAAAAAAAAMQD78//8fAEAAAAAAAAYAAAAAAAAAABz1A+D//wAAAADAAOD/A4AbAAAAAAAX0d4A/P8HAAAAAAPA//83AAAAARgAkD/MPwD/XwAAwAAguP////c/AQjw//3npBsP8P8BAID/AHD7///////7B///////4YP/AQAA/n/9v////////8/4/////4sf8AN4APB5/f//////////AP////8fwAIeAADA5////////////w/4+///f4AHwAEAAH7+/////////08PAB7g//8HeAIAAADgx/////////9BBACAAPj//wF/AAAAGDT+////////B/AAAAEA/v//+R8AAMBB8P///////z8ABwAAAOD//5//AwAANv//////////PxAAAAAA/P///z8AAAD7//////////8CAAAAAID+//8vBgAA4P//////////LwAAAAAA8P///4MAAAD+/////////38CAAAAAAD///9vAAAA4O+f/v//////AwAAAAAA8P//fwAAAOCP+cD//////x8DAAAAAAD///8DAAAAPGTv//////9/EAAAAAAA8P//DwAAAOADtP//////HwIBAAAAAAD+//8AAAAAGC7w//////9nDAAAAAAAwP//DwAAAIB/QPT/////P/IAAAAAAAD4/z8AAAAA/A8A//////+DAQAAAAAAAP//AQAAAOD/9/7/////fwAAAAAAAADAPyAAAAAA/v//v/////8HAAAAAAAAAPoBAgAAAPj///fn////PwAAAAAAAABAHwAAAACA//9//oL///8DAAAAAAAAAOABAwAAAPz//+//4P//TwAAAAAAAAAAHoYAAADg/////Qf+8w8AAAAAAAAAAMAzQAAAAPz//59/wA9+AQAAAAAAAAAA8AMAAADA////+QF44A8EAAAAAAAAAADwAAAAAP7//78HgAP4QAAAAAAAAAAAAAwAAADA////FwA4gB8EAAAAAAAAAACA8AAAAPz///8MAAPIAAEAAAAAAAAAAFD/AACA////fwBQgAQAAAAAAAAAAAAA+B8AAPD///8HAAQAAAEAAAAAAAAAAID/DwAAFv7/PwAAQIMBAAAAAAAAAAAA+P8BAACA//8BAAAoHAAAAAAAAAAAAMD/HwAAAPj/DwAAgOEFAAAAAAAAAAAA/P8HAADA/38AAAAwHhgAAAAAAAAAAMD//wMAAPj/AwAAAOZGHQAAAAAAAAAA/v//AAAA/z8AAABAgIAHAAAAAAAAAMD//x8AAPD/AwAAADgA+BAAAAAAAAAA+P//AAAA/z8AAAAAEAELBAAAAAAAAID//wcAAOD/AwAAAAAAAAAAAAAAAAAA8P9/AAAA/z8EAAAAADgCAAAAAAAAAAD//wcAAPD/QwAAAADwYwACAAAAAAAAwP8/AAAA/x8HAAAAgH8GAAAAAAAAAAD4/wMAAPD/cAAAAAD4fwAAAAAAAAAAgP8/AAAA/g8DAAAA8P8fEAAAAAAAAAD4/wAAAOD/MAAAAID//wEAAAAAAAAAgP8DAAAA/gcBAAAA+P8/AAAAAAAAAAD4PwAAAMA/AAAAAID//wcAAAAAAAAAwP8BAAAA/AMAAAAA+P9/AAAAAAAAAAD8HwAAAIAfAAAAAAD//wcAAAAAAAAAwP8AAAAA+AAAAAAA8OA/AAAAAAAAAAD8AQAAAAAAAAAAAAAB+AEQAAAAAAAA4D8AAAAAAAAAAAAAAAAfAAIAAAAAAAB+AAAAAAAAAAAAAAAAAABgAAAAAAAA4AUAAAAAAAAAAAAAAAAMAAMAAAAAAAA8AAAAAAAAAAAAAAAAgAAYAAAAAAAA4AEAAAAAAAAAAAAAAAAAwAAAAAAAAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAEAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
} as const;

/** ¿Es tierra la celda (columna, fila)? */
export function esTierra(datos: Uint8Array, columna: number, fila: number) {
  const i = fila * MUNDO.ancho + columna;
  return (datos[i >> 3] & (1 << (i & 7))) !== 0;
}

/** Descomprime los bits una sola vez. */
export function desempacar() {
  const crudo = atob(MUNDO.bits);
  const datos = new Uint8Array(crudo.length);
  for (let i = 0; i < crudo.length; i++) datos[i] = crudo.charCodeAt(i);
  return datos;
}

/** Coordenadas del mundo a celda. Devuelve null fuera del recorte. */
export function aCelda(longitud: number, latitud: number) {
  if (latitud > MUNDO.latMax || latitud < MUNDO.latMin) return null;
  const columna = Math.floor(((longitud + 180) / 360) * MUNDO.ancho);
  const fila = Math.floor(
    ((MUNDO.latMax - latitud) / (MUNDO.latMax - MUNDO.latMin)) * MUNDO.alto,
  );
  return {
    columna: Math.min(MUNDO.ancho - 1, Math.max(0, columna)),
    fila: Math.min(MUNDO.alto - 1, Math.max(0, fila)),
  };
}
